[project]
name = "contract-review-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "qdrant-client>=1.13.3",
    "ruff>=0.11.6",
]
